# Site settings
title: "Zeinab Ghannam"
description: "Research Assistant | AI for Clinical Data Analytics | Imperial College London | UK DRI (CR&T) "
url: "https://ghannamzeinab.github.io"
# Navigation menu (top bar)
include:
  - _pages

# Author sidebar profile
author:
  avatar           : "profile.png"
  name             : "Zeinab Ghannam"
  pronouns         : "she/her"
  bio              : "Research Assistant | AI for Clinical Data Analytics| Dept. of Brain Sciences, Imperial College London"
  location         : "London, UK"
  employer         : "Imperial College London"
  email            : ""

  # Academic sites (hidden if left blank)
  googlescholar    :
  orcid            :
  pubmed           :

  # Developer/social profiles
  github           : "ghannamzeinab"
  linkedin         : "in/zeinabghannam"

# Default layout for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Theme features (safe defaults)
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Europe/London

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
