author:
  avatar           : "profile.png"
  name             : "Zeinab Ghannam"
  pronouns         : "she/her"
  bio              : "Research Assistant | Clinical AI | Dept. of Brain Sciences, Imperial College London"
  location         : "London, UK"
  employer         : "Imperial College London"
  uri              : "https://www.imperial.ac.uk/brain-sciences/"
  email            : ""

  # Academic websites (leave blank to hide)
  googlescholar    :
  orcid            :
  pubmed           :

  # Developer/social profiles
  github           : "ghannamzeinab"
  linkedin         : "in/zeinabghannam"
