# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Zeinab Ghannam"
title_separator          : "-"
name                     : &name "Zeinab Ghannam"
description              : &description "AI for Clinical Research | Research Assistant at Imperial College London"
url                      : "https://ghannamzeinab.github.io"
baseurl                  : ""
repository               : "ghannamzeinab/ghannamzeinab.github.io"

# Site Author - Sidebar Info
author:
  avatar           : "profile.png" # Make sure to upload your image with this name to /images/
  name             : "Zeinab Ghannam"
  pronouns         : "she/her"
  bio              : "Research Assistant | Clinical AI | Dept. of Brain Sciences, Imperial College London"
  location         : "London, UK"
  employer         : "Imperial College London"
  uri              : "https://www.imperial.ac.uk/brain-sciences/"
  email            : "your-email@example.com" # Replace with your professional email

  # Academic websites
  googlescholar    : "https://scholar.google.com" # Optional, update if available
  orcid            : "https://orcid.org/"         # Optional
  pubmed           : ""                            # Optional
  researchgate     : ""                            # Optional

  # Repositories and developer platforms
  github           : "ghannamzeinab"

  # Social Media
  linkedin         : "in/your-linkedin"            # Replace with your LinkedIn handle
  twitter          : ""                            # Optional

# Publication Category Titles
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Other settings (no changes needed here)
teaser: 
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

comments:
  provider: false

atom_feed:
  hide: false
  path:

# SEO (optional for now)
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Social sharing
twitter:
  username: 
facebook:
  username:
og_image:

social:
  type: Person
  name: "Zeinab Ghannam"
  links: 
    - "https://www.linkedin.com/in/your-linkedin"
    - "https://github.com/ghannamzeinab"

# Analytics (optional)
analytics:
  provider: "false"

# File management
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Europe/London

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
